### ISSUE TITLE
Allow choosing other regions

### ISSUE THREAD

**Issue by tehshane** [Mathieu2301/Tuya-Cloud-API#1]
https://github.com/Mathieu2301/Tuya-Cloud-API/blob/282f2c2d350d6d45aaefde312f8932e76ae85312/main.js#L8

Currently, the library appears to be hard-coded to the EU datacenter for Tuya Cloud.

Perhaps add an option to the constructor to allow choosing other datacenters like China or North America?

Thanks for a great library!

**Comment by Mathieu2301** [comment]
Hello !
I added this option to choose the Tuya server

```javascript
tuyaCloud.connect({
  region: 'xx', // eu / us / cn / in
  clientID: 'xxxxxxxxxxxxxxxxxxxx',
  secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
});
```

Thank you ! 🙂

**Comment by tehshane** [comment]
That's awesome, thank you so much! 🎉
